name: Prüfung M324

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Upload node_modules artifact
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules

  testing:
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules


      # npm test wurde nicht gefunden als skript in package.json deswegen mit echo
      - name: Testing (echo)
        run: echo "Testing successful"

  linting:
    needs: setup
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules


      # npm run lint wurde nicht gefunden als skript in package.json deswegen mit echo
      - name: Linting
        run: echo "Linting successful"

  deployment:
    needs: [setup, testing, linting]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download node_modules artifact
        uses: actions/download-artifact@v4
        with:
          name: node_modules

      - name: Build and deploy
        run: echo "Deployment successful"
